### PR TITLE
Fixed an issue that did not stream properly when launching a system app

### PR DESCRIPTION
**Pull request by Princess-of-Sleeping**

### CODE REVIEW

**Comment by Princess-of-Sleeping** [comment]
Still it did not stream properly in welcome park(NPXS10007) or video(NPXS10010)

And don't merge this pull request.
The system freezes when you start a friend(NPXS10005).

**Comment by Princess-of-Sleeping** [comment]
The easiest way to solve this problem is to add a hook to ksceDisplaySetFrameBufInternal and keep getting parameters.
But I am convinced that it is not the best.

**Comment by xerpi** [comment]
Yeah that's a tricky thing, maybe the best way is to peek the SceIftu registers and see which fb is in the top layer.

**Comment by Princess-of-Sleeping** [comment]
I have confirmed that this issue has been fixed in another pull request, so close this pull request.
Thank you very much.

**Pull request closed without merging**
