### PR TITLE
Fix black screen on MacOS

### PR DESCRIPTION
**Pull request by xfangfang**
I got this error message from Console.app:

> [guid:0x14230000054c1337] BulkStreamHandler  Illegal Header Length of 16 was > 12.  Dropping 0 bytes already accumulated

So I changed the UVC_PAYLOAD_HEADER_SIZE from 16 to 12, and it seems everything is working perfectly.

`Only test for MacOS 10.15.`

obs

### CODE REVIEW

**Comment by xfangfang** [comment]
It doesn't seem perfect. The video is offset by 12 pixels to - X.

**Comment by xerpi** [comment]
Wow, I can't believe this was what was causing issues on macOS!

Can you try with `UVC_PAYLOAD_HEADER_SIZE 8`?

**Comment by xfangfang** [comment]
Doesn't work, the offset changed to 8. I also test with `UVC_PAYLOAD_HEADER_SIZE 2` , and it doesn't work.
This happens not only on MacOS, but also on my Android phone, so it may also happen on the other systems.

**Comment by xerpi** [comment]
I've checked the UVC 1.1 spec (`USB_Video_Payload_Uncompressed_1.1.pdf`) and the header is indeed 12 bytes:
image
You can also see "12 bytes" mentioned explicitly in: https://dri.freedesktop.org/docs/drm/media/uapi/v4l/pixfmt-meta-uvc.html

I think the problem with 12 is that the HW's colorspace converter (`ksceIftuCsc`) can't write to 12-bytes aligned address.

**Comment by xerpi** [comment]
Also checking `USB_Video_FAQ_1.1.pdf`:
image

**Comment by xfangfang** [comment]
So setting `UVC_PAYLOAD_HEADER_SIZE` to 2 for MacOS is the easiest way to handle it? Only two columns of pixels have problems.

**Comment by xerpi** [comment]
I think the problem is that `ksceIftuCsc` expects the output address to be aligned to 16 or so.

**Comment by xfangfang** [comment]
Well, it doesn't seem to be very easy to fix this problem. I'll close this PR first and see if there is any solution on MacOS.

**Comment by xerpi** [comment]
@xfangfang  I've updated master with a new commit, can you test if it works properly on macOS?

**Comment by xfangfang** [comment]
I have tried for a long time and failed. It seems that I need to learn more about C.😀

**Comment by xerpi** [comment]
It is a bit tricky, you can check the details here: https://github.com/xerpi/vita-udcd-uvc/commit/c4a9e38a5284eb61f122c2fc5f22890f31fdfec5

**Comment by xfangfang** [comment]
Thank you. When I saw the code, I understood. I didn't think `uvc_frame_req_submit_phycont` can be used in this way before.
I'm actually curious about how the header files used by this plug-in were created, such as：psp2kern/lowio/iftu.h
There's no documentation, right?

**Comment by xerpi** [comment]
@xfangfang Correct, there's no official documentation for that, even for official PSVita developers since it's kernel space. I managed to understand the usage and parameters of functions by reverse engineering SceLowio.
I also documented the registers here: https://wiki.henkaku.xyz/vita/IFTU_Registers

**Comment by xfangfang** [comment]
Thank you very much. I'll take a look at this document.
I hope I can be as good as you one day.

**Comment by xerpi** [comment]
You can find more info here: https://wiki.henkaku.xyz/vita/SceLowio

**Comment by xfangfang** [comment]
👌

**Pull request closed without merging**
